sudo: required
services:
  - docker
before_install:
  - docker build -t saikrishnaboda/fibi -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true saikrishnaboda/fibi npm test -- --coverage
after_success:
  - docker build -t saikrishnaboda/multi-client ./client
  - docker build -t saikrishnaboda/multi-server ./server
  - docker build -t saikrishnaboda/multi-worker ./worker
  - docker build -t saikrishnaboda/multi-nginx ./nginx
  - docker push saikrishnaboda/multi-client
  - docker push saikrishnaboda/multi-server
  - docker push saikrishnaboda/multi-worker
  - docker push saikrishnaboda/multi-nginx